name: Aposta Genial Build

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo " " >> .env

      - name: Get version from package.json
        id: package_version
        run: echo "PACKAGE_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/apostagenial:${{ env.PACKAGE_VERSION }}
            ${{ secrets.REGISTRY_URL }}/apostagenial:latest

      # notifier
      - name: Notify Slack - Deployment Success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: feed-git
          SLACK_USERNAME: GitHub Actions
          SLACK_COLOR: "good"
          SLACK_TITLE: "Build Successful"
          SLACK_MESSAGE: "Build of apostagenial:${{ env.PACKAGE_VERSION }} to machina hub was successful."
          SLACK_ICON: ":heavy_check_mark:"
        if: success()

      - name: Notify Slack - Deployment Failed
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: feed-git
          SLACK_USERNAME: GitHub Actions
          SLACK_COLOR: "danger"
          SLACK_TITLE: "Build Failed"
          SLACK_MESSAGE: "Build of apostagenial:${{ env.PACKAGE_VERSION }} to machina hub has failed."
          SLACK_ICON: ":x:"
        if: failure()
